In [22]:
import pandas as pd
import numpy as np

In [23]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

Load ESS data.

In [24]:
df_ess = pd.read_csv('data/ESS11e04_1.csv')

/tmp/ipykernel_2234447/3904084459.py:1: DtypeWarning: Columns (198,204,681) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ess = pd.read_csv('data/ESS11e04_1.csv')

In [25]:
df_ess.head()

,name,essround,edition,proddate,idno,cntry,dweight,pspwght,pweight,anweight,...,rinwe,inwde,jinws,jinwe,inwtm,mode,domain,prob,stratum,psu
0,ESS11e04_1,11,4.100,12.01.2026,50014,AT,1.185,0.393,0.331,0.130,...,NaN,2023-11-12 15:26:55,2023-11-12 15:21:28,2023-11-12 15:26:55,30.000,1,2.000,0.001,107,317
1,ESS11e04_1,11,4.100,12.01.2026,50030,AT,0.610,0.325,0.331,0.108,...,NaN,2023-10-18 10:44:18,2023-10-18 10:42:22,2023-10-18 10:44:18,40.000,1,1.000,0.001,69,128
2,ESS11e04_1,11,4.100,12.01.2026,50057,AT,1.392,4.000,0.331,1.324,...,NaN,2023-09-30 14:13:33,2023-09-30 14:08:31,2023-09-30 14:13:33,42.000,1,2.000,0.000,18,418
3,ESS11e04_1,11,4.100,12.01.2026,50106,AT,0.556,0.176,0.331,0.058,...,NaN,2023-06-30 15:11:21,2023-06-30 15:08:05,2023-06-30 15:11:21,34.000,1,1.000,0.001,101,295
4,ESS11e04_1,11,4.100,12.01.2026,50145,AT,0.723,1.061,0.331,0.351,...,NaN,2023-07-11 11:14:03,2023-07-11 11:10:02,2023-07-11 11:14:03,57.000,1,2.000,0.001,115,344

Restrict to France.

In [26]:
df_ess = df_ess[df_ess.cntry=='FR']

Restrict to variables of interest.

In [27]:
Variables = [
    'lrscale', 'imwbcnt', 'impenva', 'freehms', 'gincdif', 'trstplt', 'euftf', 'psppsgva', # political dimensions
    'pstplonl', # online political activity, yes or no
    'anweight', 'stratum', 'psu' # weight, stratum and primary sampling unit
             ]

In [28]:
df_ess = df_ess[Variables]

Convert all to float for consistency.

In [29]:
df_ess = df_ess.astype(float)

In [30]:
df_ess.head()

,lrscale,imwbcnt,impenva,freehms,gincdif,trstplt,euftf,psppsgva,pstplonl,anweight,stratum,psu
15376,5.000,5.000,3.000,1.000,2.000,5.000,8.000,1.000,2.000,3.354,642.000,9591.000
15377,7.000,4.000,1.000,1.000,3.000,4.000,5.000,3.000,2.000,10.405,642.000,9575.000
15378,7.000,88.000,3.000,1.000,4.000,3.000,10.000,2.000,2.000,2.159,645.000,9399.000
15379,5.000,2.000,3.000,1.000,2.000,0.000,8.000,1.000,2.000,4.693,660.000,9552.000
15380,88.000,4.000,3.000,1.000,2.000,3.000,88.000,3.000,2.000,2.116,653.000,9449.000

Remove respondents with missing values.

In [31]:
ess_label_range = {
    "psppsgva": [1, 2, 3, 4, 5],
    "impenva": [1, 2, 3, 4, 5, 6],
    "lrscale": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "euftf": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "trstplt": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "imwbcnt": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "freehms": [1, 2, 3, 4, 5],
    "gincdif": [1, 2, 3, 4, 5],
    "pstplonl": [1,2]
} # these are the answers that are not missing values, for each variable

In [32]:
for dim in ess_label_range: # for each political dimension
    values = ess_label_range[dim] # get values correpsonding to non-missing answers
    df_ess[dim] = df_ess[dim].where(df_ess[dim].isin(values), np.nan) # replace missing values with nans
    df_ess = df_ess.dropna(subset=Variables) # drop nans

In [33]:
df_ess

,lrscale,imwbcnt,impenva,freehms,gincdif,trstplt,euftf,psppsgva,pstplonl,anweight,stratum,psu
15376,5.000,5.000,3.000,1.000,2.000,5.000,8.000,1.000,2.000,3.354,642.000,9591.000
15377,7.000,4.000,1.000,1.000,3.000,4.000,5.000,3.000,2.000,10.405,642.000,9575.000
15379,5.000,2.000,3.000,1.000,2.000,0.000,8.000,1.000,2.000,4.693,660.000,9552.000
15381,8.000,9.000,1.000,1.000,2.000,6.000,5.000,3.000,2.000,2.499,658.000,9387.000
15383,8.000,1.000,1.000,1.000,2.000,0.000,1.000,2.000,2.000,2.294,652.000,9470.000
...,...,...,...,...,...,...,...,...,...,...,...,...
17141,5.000,6.000,1.000,1.000,2.000,5.000,6.000,3.000,2.000,2.740,643.000,9443.000
17143,6.000,3.000,3.000,1.000,3.000,2.000,7.000,2.000,1.000,3.645,660.000,9369.000
17144,4.000,4.000,2.000,1.000,2.000,6.000,6.000,3.000,2.000,4.458,659.000,9412.000
17145,6.000,4.000,4.000,1.000,2.000,3.000,4.000,3.000,2.000,3.686,642.000,9542.000
17146,3.000,5.000,2.000,1.000,3.000,3.000,5.000,1.000,1.000,3.256,642.000,9541.000

Reorder some dimensions to match the ordering of the X data.

In [34]:
df_ess['trstplt'] = 10.0 - df_ess['trstplt']
df_ess['imwbcnt'] = 10.0 - df_ess['imwbcnt']
df_ess['psppsgva'] = 6.0 - df_ess['psppsgva']
df_ess['euftf'] = 10.0 - df_ess['euftf']

Reset index.

In [35]:
df_ess = df_ess.reset_index(drop=True)

Rename dimensions.

In [36]:
VariableNames = {
    'lrscale': 'Left-Right', 
    'trstplt': 'Anti-elitism', 
    'euftf': 'EU integration', 
    'freehms': 'Social liberalism', 
    'impenva': 'Environment', 
    'imwbcnt': 'Immigration', 
    'psppsgva': 'Direct democracy', 
    'gincdif': 'Redistribution',
    'pstplonl':'online_political_activity'
    }

In [37]:
df_ess = df_ess.rename(columns = VariableNames)

Show.

In [38]:
df_ess

,Left-Right,Immigration,Environment,Social liberalism,Redistribution,Anti-elitism,EU integration,Direct democracy,online_political_activity,anweight,stratum,psu
0,5.000,5.000,3.000,1.000,2.000,5.000,2.000,5.000,2.000,3.354,642.000,9591.000
1,7.000,6.000,1.000,1.000,3.000,6.000,5.000,3.000,2.000,10.405,642.000,9575.000
2,5.000,8.000,3.000,1.000,2.000,10.000,2.000,5.000,2.000,4.693,660.000,9552.000
3,8.000,1.000,1.000,1.000,2.000,4.000,5.000,3.000,2.000,2.499,658.000,9387.000
4,8.000,9.000,1.000,1.000,2.000,10.000,9.000,4.000,2.000,2.294,652.000,9470.000
...,...,...,...,...,...,...,...,...,...,...,...,...
1412,5.000,4.000,1.000,1.000,2.000,5.000,4.000,3.000,2.000,2.740,643.000,9443.000
1413,6.000,7.000,3.000,1.000,3.000,8.000,3.000,4.000,1.000,3.645,660.000,9369.000
1414,4.000,6.000,2.000,1.000,2.000,4.000,4.000,3.000,2.000,4.458,659.000,9412.000
1415,6.000,6.000,4.000,1.000,2.000,7.000,6.000,3.000,2.000,3.686,642.000,9542.000
1416,3.000,5.000,2.000,1.000,3.000,7.000,5.000,5.000,1.000,3.256,642.000,9541.000

Create an additional dataframe for respondents who declare an online political activity.

In [39]:
df_ess_pao = df_ess[df_ess.online_political_activity==1].reset_index(drop=True)

Show.

In [40]:
df_ess_pao

,Left-Right,Immigration,Environment,Social liberalism,Redistribution,Anti-elitism,EU integration,Direct democracy,online_political_activity,anweight,stratum,psu
0,5.000,5.000,1.000,1.000,1.000,6.000,0.000,4.000,1.000,3.815,649.000,9483.000
1,2.000,5.000,2.000,1.000,1.000,6.000,4.000,4.000,1.000,4.187,658.000,9566.000
2,8.000,5.000,4.000,1.000,5.000,5.000,7.000,4.000,1.000,3.346,642.000,9548.000
3,3.000,5.000,1.000,1.000,1.000,5.000,0.000,3.000,1.000,2.541,650.000,9508.000
4,2.000,5.000,2.000,3.000,3.000,8.000,4.000,4.000,1.000,2.411,632.000,9328.000
...,...,...,...,...,...,...,...,...,...,...,...,...
258,0.000,1.000,1.000,1.000,2.000,5.000,1.000,3.000,1.000,3.669,642.000,9596.000
259,4.000,0.000,4.000,1.000,4.000,9.000,5.000,5.000,1.000,3.621,642.000,9537.000
260,3.000,1.000,1.000,1.000,1.000,7.000,3.000,4.000,1.000,2.372,662.000,9531.000
261,6.000,7.000,3.000,1.000,3.000,8.000,3.000,4.000,1.000,3.645,660.000,9369.000
262,3.000,5.000,2.000,1.000,3.000,7.000,5.000,5.000,1.000,3.256,642.000,9541.000

Export.

In [41]:
df_ess.to_csv('data/ESS11_preprocessed.csv', index=False)

In [42]:
df_ess_pao.to_csv('data/ESS11-pao_preprocessed.csv', index=False)